services:
  mobility-alerter:
    image: ghcr.io/phd-kerger/mobility-alerter:v1.1
    volumes:
      - ./config.yaml:/app/config.yaml:ro
      # Add all the logs referenced in the config.yaml's of the collectors here
      # - /root/gbfs-collector/log:/app/logs/gbfs-collector/log:ro
      # - /root/gtfs-collector/log:/app/logs/gtfs-collector/log:ro
      # - /root/nextbike-collector/log:/app/logs/nextbike-collector/log:ro
    restart: unless-stopped
  
